My-Web-Project(LandMarks)/Controllers/CultureEventController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Services.IServices;
using MyWebProject.Infrastructure.Data.Common;
using MyWebProject.Infrastructure.Data.Models;

namespace My_Web_Project_LandMarks_.Controllers
{

    public class CultureEventController : Controller
    {
        private readonly ICultureEventService service;
        private readonly UserManager<Users> user;
        private readonly IRepository repo;

        public CultureEventController(ICultureEventService _service,
            UserManager<Users> _user,
            IRepository _repo)
        {
            service = _service;
            user = _user;
            repo = _repo;
        }


        /// <summary>
        /// The method returns a city by the given Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>city by the given Id</returns>
        [HttpGet]
        public async Task<IActionResult> EventByTownId(int id)
        {
            var model = await service.EventByTownId(id);

            return View(model);
        }



        /// <summary>
        /// A method to get the changed user and add event
        /// collections to the current user.
        /// </summary>
        /// <param name="eventId"></param>
        /// <returns> Message to seccssusfuly added</returns>

        [Authorize]
        public async Task<IActionResult> AddEventByUserCollection(int eventId, string choiceBtn)
        {

            var currentEvent = await repo.GetByIdAsync<Cultural_events>(eventId);

            if (currentEvent != null)
            {
                if (choiceBtn == "Може би" && choiceBtn != null
                    && string.IsNullOrEmpty(choiceBtn))
                {
                    currentEvent.Maybe = true;
                }
                else if (choiceBtn == "Ще присъствам" && choiceBtn != null
                    && string.IsNullOrEmpty(choiceBtn))
                {
                    currentEvent.Going = true;
                }

                var currentUser = user.FindByNameAsync(User!.Identity!.Name!.ToUpper()).Result;

                var set = await repo.GetByIdAsync<Users>(currentUser!.Id);


                var check = repo.AllReadonly<Cultural_events>().Where(x => x.AllUsers.Any(a => a.Id == currentUser.Id));


                if (check.Any(a => a.Id == currentEvent.Id) == false)
                {
                    currentUser!.CulturalEvents.Add(currentEvent);

                    await repo.SaveChangesAsync();
                }

                return RedirectToAction("GetAllEvent");

            }

            return RedirectToAction("GetAllEvent");
        }


        /// <summary>
        /// The method takes all cities
        /// </summary>
        /// <returns>All Towns collection</returns>
        [HttpGet]
        public async Task<IActionResult> GetAllEvent()
        {
            var model = await service.AllEvent();

            return View(model);
        }


    }
}

My-Web-Project(LandMarks)/Controllers/JourneyController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Services.IServices;

namespace My_Web_Project_LandMarks_.Controllers
{
    public class JourneyController : Controller
    {
        private readonly IJourneyServise service;

        public JourneyController(IJourneyServise _service)
        {
            service = _service;
        }


        /// <summary>
        /// The method returns a collection of all journeys
        /// accessed by a service
        /// </summary>
        /// <returns>Collection of all journeys</returns>
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var model = await service.GetAll();

            return View(model);
        }


        /// <summary>
        /// The method returns the received trip idand passes it through a service method
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Рeturns a trip with the given id</returns>
        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            var model = await service.GetById(id);

            return View(model);
        }


    }
}

My-Web-Project(LandMarks)/Controllers/LandMarkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Models.LandMarkModel;
using MyWebProject.Core.Services.IServices;

namespace My_Web_Project_LandMarks_.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class LandMarkController : Controller
    {
        private readonly ILandmarkService service;


        public LandMarkController(ILandmarkService _service)
        {
            service = _service;
        }


        /// <summary>
        /// The method searches for prominence by the given id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>returns a landmark with the given id</returns>
        [HttpGet]
        public async Task<IActionResult> LandMarkById(int id)
        {
            if (!await service.ExistById(id))
            {
                ModelState.AddModelError("", "Not Correct data");
            }

            var model = await service.GetById(id);

            return View(model);
        }


        /// <summary>
        /// The method rattles all sights
        /// </summary>
        /// <returns>Collection of landmarks</returns>
        [HttpGet]
        public async Task<IActionResult> AllLandmark()
        {
            var allLandMark = await service.GetAllLandmark();

            if (allLandMark == null)
            {
                return View();
            }

            return View(allLandMark);
        }


        /// <summary>
        /// The method loads a view for the user to add a landmark 
        /// as the model loads the categories preloaded dropdown menu
        /// </summary>
        /// <returns>View of field to write of useer</returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AddUserSuggestions()
        {
            var model = new AddLandMarkViewModel()
            {
                Category = await service.AllCategory()
            };

            return View(model);
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> UpRatting(int id)
        {
            var result = await service.UpRattingPoint(id);

            return RedirectToAction("AllLandmark"); 
        }



        /// <summary>
        ///  Adding the user-suggested landmark to the pending admin approval table
        /// </summary>
        /// <param name="model"></param>
        /// <returns>resdirect to index page of all landmarks</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddUserSuggestions(AddLandMarkViewModel model)
        {

            model.UserName = User.Identity?.Name;
            await service.AddLandMarkOfUsers(model);

            return RedirectToAction("AllLandmark");
        }
    }
}

My-Web-Project(LandMarks)/Controllers/Top10destinationController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Services.IServices;

namespace My_Web_Project_LandMarks_.Controllers
{
    public class Top10destinationController : Controller
    {
        private readonly ITop10Destination service;
        private readonly IMysteryPlace mpService;

        public Top10destinationController(ITop10Destination _service,
            IMysteryPlace _mpService)
        {
            service = _service;
            mpService = _mpService;
        }

        /// <summary>
        /// The method returns a collection of landmarks with a rating above 9, taking the top 10
        /// </summary>
        /// <returns>Collection</returns>
        public async Task<IActionResult> Get10Landmark()
        {
            var model = await service.Get10TopLandMark();

            return View(model);
        }

        /// <summary>
        /// The method returns a collection of landmarks with a rating above 
        /// 9 that have an address added to a video about the landmark
        /// </summary>
        /// <returns>Collection of landmarks</returns>
        public async Task<IActionResult> MysteryPlaces()
        {
            var model = await mpService.MysteryPlaces();

            return View(model);
        }


        /// <summary>
        /// The method returns a collection of landmarks and their 
        /// associated cities with a rating greater than 9
        /// </summary>
        /// <returns>Collection of landmarks</returns>
        public async Task<IActionResult> AllLandMarkByTown()
        {
            var model = await service.AllLandMarkByTown();

            return View(model);
        }

    }
}

My-Web-Project(LandMarks)/Controllers/TownController.cs
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Services.IServices;

namespace My_Web_Project_LandMarks_.Controllers
{
    public class TownController : Controller
    {
        public readonly ITownService service;

        public TownController(ITownService _service)
        {
            service = _service;
        }


        /// <summary>
        /// The method selects six cities from the database
        /// </summary>
        /// <returns>Collection of towns</returns>
        [HttpGet]
        public async Task<IActionResult> All()
        {
            var rest = await service.AllTowns();

            return View(rest);
        }


        /// <summary>
        /// The method searches for a city by the specified id
        /// </summary>
        /// <param name="id"></param>
        /// <returns“Returns the city its cultural events and attractions, if available</returns>
        [HttpGet]
        public async Task<IActionResult> GetTown(int id)
        {
            var rest = await service.TownsById(id);

            if (rest != null)
            {
                return View(rest);
            }

            return View();
        }

    }
}

My-Web-Project(LandMarks)/Views/Town/All.cshtml
@using MyWebProject.Core.Models.Town;
@model IEnumerable<TownViewModelAll>

<head>
    <link rel="stylesheet" href="~/css/All CSS file/TownCustomCSS/AllTownsCss.css" asp-append-version="true" />
</head>

<div id="allTown">

    <div id="Info">
        <h3>Може да видите още...</h3>
        <hr />
        <ul type="none">
            <li> @Html.ActionLink("Мистериозни места", "MysteryPlaces", "Top10destination", null, new { @class = "myactionlink" })</li>
            <li> @Html.ActionLink("Забележителностите с най-висок рейтинг", "Get10Landmark", "Top10destination", null, new { @class = "myactionlink" })</li>
            <li> @Html.ActionLink("Забележителностите на България", "AllLandmark", "LandMark", null, new { @class = "myactionlink" })</li>
            <li> @Html.ActionLink("Екскурзии и почивки", "GetAll", "Journey", null, new { @class = "myactionlink" })</li>
            <li> @Html.ActionLink("Културни събития", "GetAllEvent", "CultureEvent", null, new { @class = "myactionlink" })</li>
        </ul>
    </div>

    @foreach (var pic in Model)
    {
        var picture = pic.Picture.FirstOrDefault(x => x.TownId != null);

        <div id="containerTown">
            <img src="@picture?.UrlImgAddres" alt="Town" />
            <div id="texts">
                <h4>@pic.Name</h4>
                <hr>
                <p>@pic.Description.Substring(0, 380)...</p>
                <a class="btn btn-primary" asp-controller="Town" asp-action="GetTown" asp-route-id="@pic.Id" method="post">Към Градът</a>
            </div>
        </div>
    }
</div>

My-Web-Project(LandMarks)/Views/Town/GetTown.cshtml
@using MyWebProject.Core.Models.Town;
@model TownViewModelGetTown
@{
    bool first = true;
}

<head>
    <link rel="stylesheet" href="~/css/All CSS file/TownCustomCSS/TownCss.css" asp-append-version="true" />
</head>



<div class="hero">

    <div class="text-lg-center">
        <p style="font-size:50px;"> @Model.Name</p>
        <hr />
        <br />
    </div>
    @{
        var pic = Model.Picture.Where(a => a.TownId == Model.Id && a.LandMarkId == null).ToList();
    }


    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner" style="margin-left:150px">
            @foreach (var sa in pic)
            {
                <div class="carousel-item @(first ? "active" : string.Empty)">

                    <img class="d-block w-75" style="height:500px"
                         src="@sa.UrlImgAddres" alt="Town Picture">

                </div>

                first = false;
            }
        </div>
        <div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <br />




    <div id="descript" class="container">
        <div class="row">
            <div id="desc"><p>@Model.Description</p></div>
            <br />
            <hr />
        </div>
    </div>
    <br />

    @{
        var pict = Model.Picture.ToList();
        var land = Model.Landmarks.ToList();
    }

    @if (land.Count >= 3)
    {
        <div class="container">
            <div class="text-lg-center">

                <p style=" font-size:50px;">Забележителности</p>
                <hr />
            </div>
            <div class="row">
                @for (int i = 0; i < 3; i++)
                {
                    var picture = pict.FirstOrDefault(x => x.LandMarkId == land[i].Id);

                    <div id="cardElement">
                        <img src="@picture?.UrlImgAddres" class="card-img-top" alt="...">
                        <div id="secText">
                            <h5>@land[i].Name.ToString()</h5>
                            <hr />
                            <p>@land[i].Description.Substring(0, 60)...</p>
                            <a class="btn btn-primary" asp-route-id="@land[i].Id" asp-controller="landMark" asp-action="LandMarkById">Научи повече</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    <br />
    <hr />

    @{
        var culEvent = Model.cultural_Events.ToList();
    }

    <div class="container">
        <div class="text-lg-center">
            <p style="font-size:50px;">Културни Събития</p>
            <hr />
        </div>
        <div class="row">
            @for (int i = 0; i < 3; i++)
            {
                <div id="cardElement">
                    <img src="@culEvent[i].ImageURL" class="card-img-top" alt="...">
                    <div id="secText">
                        <h5>@culEvent[i].Name.ToString()</h5>
                        <hr />
                        @if (culEvent[i].Description.Length < 50)
                        {
                            <p>@culEvent[i].Description.Substring(0, culEvent[i].Description.Length)...</p>
                        }
                        else
                        {
                            <p>@culEvent[i].Description.Substring(0, 60)...</p>
                        }
                        <a id="eventss" class="btn btn-primary" asp-route-id="@culEvent[i].Id" asp-controller="CultureEvent" asp-action="EventByTownId">Научи повече</a>
                    </div>
                </div>
            }
        </div>
    </div>
    <hr />

</div>

My-Web-Project(LandMarks)/Views/Town/Town.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}