My-Web-Project(LandMarks)/Areas/Administrator/Controllers/HomeAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyWebProject.Core.Models.AdminHomeModel;
using MyWebProject.Core.Services.IServices;
using MyWebProject.Core.Services.Services;

namespace My_Web_Project_LandMarks_.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class HomeAdminController : Controller
    {

        private readonly IHomeService service;

        public HomeAdminController(IHomeService _service)
        {
            service = _service;
        }





        /// <summary>
        /// View all controlers(options) access to admin area
        /// to create , added, edit and removed.
        /// </summary>
        /// <returns>All options controllers</returns>
        public IActionResult Index()
        {
            var model =new AdminHomeModelAllData();
            var setData =  service.AllData(model);


            return View(model);
        }
    }
}

My-Web-Project(LandMarks)/Areas/Administrator/Views/Shared/View.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

My-Web-Project(LandMarks)/Areas/Administrator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Admin Area css/AdminIdexPage.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Administrator" asp-controller="HomeAdmin" asp-action="Index">Admin Panel</a>

                <a> @Html.ActionLink("Wait for Approval landmark", "GetByUser", "OptionLandMark", null, new { @class = "myactionlink1" })</a>
                <a> @Html.ActionLink("Wait for Approval Picture", "ByUserPicture", "OptionPictures", null, new { @class = "myactionlink2" })</a>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div>
            <p>Admin panel</p>
            <p>Section to right side is statistic data of all activ item </p>
            <p>&copy; 2022 - 2023 - Пътеводител на Българските забележителности</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>